name: mashtoz_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flip_card: ^0.7.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.18
  provider: ^6.0.5
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_svg: ^1.0.0
  eva_icons_flutter: ^3.1.0
  backdrop: ^0.8.1
  formz: ^0.4.1
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.3
  tab_indicator_styler: ^2.0.0
  pin_code_fields: ^7.3.0
  word_break_text: ^0.1.0
  youtube_player_flutter: ^8.1.2
  photo_view: ^0.14.0
#    git:
#      url: https://github.com/bluefireteam/photo_view
#      ref: master
#  jsonml: ^0.1.9
  
  screen_brightness: ^0.2.0
  
  simple_shadow: ^0.3.0
  video_player: ^2.2.4
  native_device_orientation: ^1.1.2
  wakelock: ^0.6.1+2
  #auto_orientation: ^2.2.1
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  
  share_plus: ^6.3.0
  url_launcher: ^6.1.3
  flutter_share_me: ^1.3.0
  flutter_launcher_icons: ^0.13.0


  rename: ^2.0.1
  firebase_core: ^2.9.0
  responsive_grid_list: ^1.2.4
  firebase_messaging: ^14.4.0
  overlay_support: ^2.0.1
  cloud_functions: ^4.0.8
  flutter_local_notifications: ^9.1.3
  rxdart: ^0.27.4
  #google_sign_in: ^5.3.3
  flutter_facebook_auth: ^5.0.7
  firebase_auth: ^4.2.6
  flutter_smart_dialog: ^4.0.9+5
  table_calendar: ^3.0.6
  syncfusion_localizations: ^20.2.36
  flutter_native_splash: ^2.1.6
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  localization: ^2.1.0
  from_css_color: ^2.0.0
  rive: ^0.10.2
  rive_splash_screen: ^0.1.1
  flare_flutter: ^3.0.2
  
  cross_connectivity: ^3.0.5
  velocity_x: ^3.6.0
  google_sign_in: ^6.0.2
  json_helpers: ^0.1.5
  platform_device_id: ^1.0.1
  fluttertoast: ^8.2.1
  loading_overlay: ^0.3.0
  flutter_html: ^3.0.0-alpha.6
  flutter_html_all: ^3.0.0-alpha.6
  webview_flutter: ^2.0.4
  youtube: ^1.0.1
  youtube_parser: ^2.0.0
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.0
  baseflow_plugin_template: ^2.1.1

  
  

  
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_mashtoz.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#53424c"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  fonts:
    - family: ArshaluyseArtU
      fonts:
        - asset: assets/fonts/ArshaluyseArtU-Bold.ttf
          style: normal
          weight: 700
    - family: GHEAGrapalat
      fonts:
        - asset: assets/fonts/GHEAGpalatBld.otf
        - asset: assets/fonts/GHEAGrapalatBlit.otf
        - asset: assets/fonts/GHEAGrapalatRit.otf
        - asset: assets/fonts/GHEAGrpalatReg.otf
          style: normal
          
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/i18n/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
